#!/bin/bash

ln -s ~/uni-linux-config/bash_profile ~/.bash_profile
ln -s ~/uni-linux-config/bash_profile ~/.bashrc
ln -s ~/uni-linux-config/Xresources ~/.Xresources

xrdb ~/.Xresources
source ~/.bash_profile
