#!/bin/sh

echo "ArgCount: $#"
if [ $# -eq 2 ]; then
	alias="alias $1='$2'"
	echo $alias >> ~/.bash_profile
	echo "Alias: $alias"
elif [ $# -eq 3 ]; then
	alias="alias $1='$2' # $3"
	echo $alias >> ~/.bash_profile
	echo "Alias: $alias"
fi
